version: '3'

services:
  api:
    # docker run -d -p 8000:8000 data-tracker-backend pipenv run start 
    build: ./api
    command: pipenv run start
    image : data-tracker-backend
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
  
  front:
    build: ./front
    command: npm start
    image : data-tracker-front
    volumes:
      - ./front:/front
    ports:
      - "5000:5000"
