version: '3'

services: 
    web:
        build: .
        command: pipenv run start
        image : data-tracker-backend
        volumes: 
            - .:/api/
        ports: 
            - "8000:8000"
